"""OpenFOAM function objects for post-processing.

Generates function object configurations for:
- age: Liquid Mean Age field computation
- histogram: Volume-weighted field distributions (velocity, age)
- volFieldValue: Field statistics (mean, min, max)

These are written to system/functionObjects and included in controlDict.
"""

from pathlib import Path
from typing import Any


class FunctionObjectsGenerator:
    """Generate OpenFOAM function objects configuration."""

    def generate_all(
        self,
        case_dir: Path,
        config_context: dict[str, Any],
    ) -> list[str]:
        """Generate all function objects for a mixing analysis.

        Args:
            case_dir: OpenFOAM case directory.
            config_context: Context from CaseBuilder with config info.

        Returns:
            List of function object names created.
        """
        fo_content = self._generate_function_objects_file(config_context)

        # Add per-region function objects if regions are defined
        regions = config_context.get("regions", [])
        if regions:
            fo_content += self.generate_region_function_objects(regions)

        # Add slice surfaces for visualization (if tank height is available)
        tank = config_context.get("tank", {})
        tank_height = tank.get("height", 0)
        if tank_height > 0:
            slice_heights = self._compute_default_slice_heights(tank_height)
            fo_content += self.generate_slice_surfaces(slice_heights)

        # Write to system/functionObjects
        fo_path = case_dir / "system" / "functionObjects"
        fo_path.write_text(fo_content)

        fo_names = [
            "age",
            "histogramVelocity",
            "histogramAge",
            "volFieldValueGlobal",
            "outletAgeFlowWeighted",
            "outletFlowRate",
            "fieldMinMax",
            "residuals",
        ]

        # Add per-region function object names
        for region in regions:
            region_id = region["id"]
            fo_names.append(f"histogramVelocity_{region_id}")
            fo_names.append(f"volFieldValue_{region_id}")

        # Add slice surface names
        if tank_height > 0:
            slice_heights = self._compute_default_slice_heights(tank_height)
            for z in slice_heights:
                fo_names.append(f"sliceZ_{int(z * 1000)}mm")

        return fo_names

    def _compute_default_slice_heights(self, tank_height: float) -> list[float]:
        """Compute default slice heights for visualization.

        Creates slices at 10%, 25%, 50%, 75%, and 90% of tank height.

        Args:
            tank_height: Tank height in meters.

        Returns:
            List of z-coordinates in meters.
        """
        fractions = [0.10, 0.25, 0.50, 0.75, 0.90]
        return [f * tank_height for f in fractions]

    def _generate_function_objects_file(self, ctx: dict[str, Any]) -> str:
        """Generate the functionObjects include file."""
        # Get outlet patches for age sampling
        outlet_names = [o["id"] for o in ctx.get("outlets", [])]
        outlet_patches = " ".join(outlet_names) if outlet_names else "outlet"

        # Histogram settings
        n_bins = 100
        velocity_max = 1.0  # Will be auto-scaled by OpenFOAM
        age_max = ctx.get("theoretical_hrt", 24.0) * 3600 * 3  # 3x HRT in seconds

        return f"""// Function objects for mixing analysis
// Auto-generated by mixing-cfd-mcp

age
{{
    type            age;
    libs            (fieldFunctionObjects);

    enabled         true;
    writeControl    writeTime;
    executeControl  writeTime;

    // Diffusion coefficient (usually 0 for plug-flow reference)
    diffusion       false;

    // Name of age field
    phi             phi;
    rho             rho;
}}

histogramVelocity
{{
    type            histogram;
    libs            (fieldFunctionObjects);

    enabled         true;
    writeControl    writeTime;
    executeControl  writeTime;

    // Field to histogram
    field           mag(U);

    // Number of bins
    nBins           {n_bins};

    // Range (auto if not specified)
    // max             {velocity_max};

    // Weight by cell volume for accurate distributions
    weightField     V;

    // Set region (entire domain)
    setFormat       raw;
}}

histogramAge
{{
    type            histogram;
    libs            (fieldFunctionObjects);

    enabled         true;
    writeControl    writeTime;
    executeControl  writeTime;

    field           age;
    nBins           {n_bins};
    max             {age_max:.1f};
    weightField     V;
    setFormat       raw;
}}

volFieldValueGlobal
{{
    type            volFieldValue;
    libs            (fieldFunctionObjects);

    enabled         true;
    writeControl    writeTime;
    executeControl  writeTime;

    // Region: entire domain
    regionType      all;

    // Fields to process
    fields          (U age p);

    // Operations
    operation       volAverage;

    // Also compute weighted average
    weightField     none;
}}

// Flow-weighted mean age at outlet for tau_outlet computation
// tau_outlet = sum(phi * age) / sum(phi) at outlet faces
outletAgeFlowWeighted
{{
    type            surfaceFieldValue;
    libs            (fieldFunctionObjects);

    enabled         true;
    writeControl    writeTime;
    executeControl  writeTime;

    // Region: outlet patches
    regionType      patch;
    name            {outlet_patches};

    // Age field only for tau_outlet
    fields          (age);

    // Flow-weighted average: sum(phi * age) / sum(phi)
    operation       weightedAverage;
    weightField     phi;
}}

// Outlet flow rate for mass balance verification
outletFlowRate
{{
    type            surfaceFieldValue;
    libs            (fieldFunctionObjects);

    enabled         true;
    writeControl    writeTime;
    executeControl  writeTime;

    regionType      patch;
    name            {outlet_patches};

    fields          (phi);
    operation       sum;
}}

fieldMinMax
{{
    type            fieldMinMax;
    libs            (fieldFunctionObjects);

    enabled         true;
    writeControl    writeTime;
    executeControl  writeTime;

    // Mode: magnitude for vectors
    mode            magnitude;

    // Fields to track
    fields          (U age p);

    // Log to file
    log             true;
    write           true;
}}

residuals
{{
    type            residuals;
    libs            (utilityFunctionObjects);

    enabled         true;
    writeControl    timeStep;
    writeInterval   1;

    fields          (p U age);
}}
"""

    def generate_slice_surfaces(
        self,
        z_heights: list[float],
        fields: list[str] | None = None,
    ) -> str:
        """Generate slice surface function objects for visualization.

        Creates horizontal cutting planes at specified z-heights that
        output VTK files with field data for visualization.

        Args:
            z_heights: List of z-coordinates in meters.
            fields: Fields to sample. Defaults to ["U", "age"].

        Returns:
            OpenFOAM function object configuration string.
        """
        if fields is None:
            fields = ["U", "age"]

        fields_str = " ".join(fields)
        content = "\n// Horizontal slice surfaces for visualization\n"

        for z in z_heights:
            z_mm = int(z * 1000)
            surface_name = f"sliceZ_{z_mm}mm"

            content += f"""
{surface_name}
{{
    type            surfaces;
    libs            (sampling);

    enabled         true;
    writeControl    writeTime;
    executeControl  writeTime;

    // Output format
    surfaceFormat   vtk;

    // Fields to sample
    fields          ({fields_str});

    // Interpolation scheme
    interpolationScheme cellPoint;

    // Surface definitions
    surfaces
    {{
        {surface_name}
        {{
            type            plane;
            point           (0 0 {z:.6f});
            normal          (0 0 1);
            interpolate     true;
        }}
    }}
}}
"""

        return content

    def generate_region_function_objects(
        self,
        regions: list[dict[str, Any]],
    ) -> str:
        """Generate function objects for named analysis regions.

        Creates per-region:
        - volFieldValue for average velocity/age
        - histogramVelocity for dead zone analysis

        Args:
            regions: List of region definitions with id, shape, position, dimensions.

        Returns:
            OpenFOAM function object configuration string.
        """
        content = "\n// Per-region function objects\n"

        for region in regions:
            region_id = region["id"]
            region_name = region.get("name", region_id)

            # Per-region velocity histogram for dead zone analysis
            content += f"""
// Histogram for region '{region_name}'
histogramVelocity_{region_id}
{{
    type            histogram;
    libs            (fieldFunctionObjects);

    enabled         true;
    writeControl    writeTime;
    executeControl  writeTime;

    field           mag(U);
    nBins           100;
    weightField     V;
    setFormat       raw;

    // Restrict to cellZone
    regionType      cellZone;
    name            {region_id};
}}

// Average values for region '{region_name}'
volFieldValue_{region_id}
{{
    type            volFieldValue;
    libs            (fieldFunctionObjects);

    enabled         true;
    writeControl    writeTime;
    executeControl  writeTime;

    regionType      cellZone;
    name            {region_id};

    fields          (U age);
    operation       volAverage;
}}
"""

        return content


def write_function_objects(case_dir: Path, ctx: dict[str, Any]) -> list[str]:
    """Convenience function to write function objects.

    Args:
        case_dir: OpenFOAM case directory.
        ctx: Configuration context from CaseBuilder.

    Returns:
        List of function object names created.
    """
    generator = FunctionObjectsGenerator()
    return generator.generate_all(case_dir, ctx)
