"""MRF (Multiple Reference Frame) zone generation for mechanical mixers.

Generates OpenFOAM MRF configuration including:
- constant/MRFProperties file with zone definitions
- topoSetDict actions for cylindrical or surface-based cellZones
- Support for multi-impeller configurations with multiple MRF zones
"""

import math
from pathlib import Path
from typing import Any


class MRFGenerator:
    """Generate MRFProperties and cellZone definitions for impeller zones.

    Supports:
    - Single and multi-impeller configurations
    - Cylindrical MRF zones (cylinderToCell)
    - Surface-based MRF zones (surfaceToCell) from STL/OBJ files
    - Multiple MRF zones for multi-impeller mixers
    """

    def generate(
        self,
        case_dir: Path,
        ctx: dict[str, Any],
    ) -> bool:
        """Generate MRF configuration if mechanical mixers are present.

        Args:
            case_dir: OpenFOAM case directory.
            ctx: Configuration context from CaseBuilder.

        Returns:
            True if MRF files were generated, False otherwise.
        """
        mixers = ctx.get("mixing_elements", {}).get("mechanical_mixers", [])
        if not mixers:
            return False

        # Generate MRFProperties
        mrf_content = self._generate_mrf_properties(mixers)
        mrf_path = case_dir / "constant" / "MRFProperties"
        mrf_path.write_text(mrf_content)

        return True

    def _generate_mrf_properties(self, mixers: list[dict[str, Any]]) -> str:
        """Generate MRFProperties file content.

        Args:
            mixers: List of mechanical mixer context dictionaries.

        Returns:
            OpenFOAM MRFProperties file content.
        """
        content = """FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      MRFProperties;
}

// MRF zones for mechanical mixers
// Auto-generated by mixing-cfd-mcp Phase 2

"""
        for mixer in mixers:
            mixer_id = mixer["id"]
            impellers = mixer.get("impellers", [])

            if not impellers:
                # Legacy single-impeller mode
                impellers = [
                    {
                        "id": f"{mixer_id}_impeller",
                        "position_m": mixer.get("impeller_position_m", 1.0),
                        "diameter_m": mixer.get("impeller_diameter_m", 0.5),
                        "effective_mrf_radius": mixer.get("effective_mrf_radius", 0.275),
                        "effective_mrf_height": mixer.get("effective_mrf_height", 0.25),
                    }
                ]

            # Generate MRF zone for each impeller
            for imp in impellers:
                content += self._generate_single_mrf_zone(mixer, imp)

        return content

    def _generate_single_mrf_zone(
        self,
        mixer: dict[str, Any],
        impeller: dict[str, Any],
    ) -> str:
        """Generate a single MRF zone entry.

        Args:
            mixer: Mixer context dictionary.
            impeller: Impeller context dictionary.

        Returns:
            MRF zone entry string.
        """
        zone_id = f"mrf_{impeller['id']}"
        cell_zone = f"impellerZone_{impeller['id']}"

        # Get impeller position along shaft
        mount_pos = mixer.get("mount_position", {"x": 0, "y": 0, "z": 0})
        shaft_axis = mixer.get("shaft_axis", {"x": 0, "y": 0, "z": -1})
        imp_position_m = impeller.get("position_m", 1.0)

        # Calculate impeller center position
        # Origin is at impeller center = mount_position + shaft_axis * impeller_position_m
        origin_x = mount_pos["x"] + shaft_axis["x"] * imp_position_m
        origin_y = mount_pos["y"] + shaft_axis["y"] * imp_position_m
        origin_z = mount_pos["z"] + shaft_axis["z"] * imp_position_m

        # Get rotation parameters
        omega_rad_s = mixer.get("omega_rad_s", 10.472)  # Default ~100 RPM

        # Axis is shaft direction (normalized)
        axis_mag = math.sqrt(shaft_axis["x"] ** 2 + shaft_axis["y"] ** 2 + shaft_axis["z"] ** 2)
        if axis_mag > 0:
            axis_x = shaft_axis["x"] / axis_mag
            axis_y = shaft_axis["y"] / axis_mag
            axis_z = shaft_axis["z"] / axis_mag
        else:
            axis_x, axis_y, axis_z = 0, 0, -1  # Default vertical

        return f"""
{zone_id}
{{
    cellZone        {cell_zone};
    active          true;

    // Rotation axis definition
    origin          ({origin_x:.6f} {origin_y:.6f} {origin_z:.6f});
    axis            ({axis_x:.6f} {axis_y:.6f} {axis_z:.6f});
    omega           {omega_rad_s:.6f};  // rad/s

    // Patches that should not rotate within this zone
    // (e.g., baffles, tank walls inside the MRF region)
    nonRotatingPatches ();
}}
"""

    def generate_topo_set_actions(
        self,
        ctx: dict[str, Any],
    ) -> list[str]:
        """Generate topoSetDict actions for MRF cellZones.

        Args:
            ctx: Configuration context from CaseBuilder.

        Returns:
            List of topoSetDict action strings for MRF zones.
        """
        mixers = ctx.get("mixing_elements", {}).get("mechanical_mixers", [])
        actions = []

        for mixer in mixers:
            mixer_id = mixer["id"]
            impellers = mixer.get("impellers", [])

            if not impellers:
                # Legacy single-impeller mode
                impellers = [
                    {
                        "id": f"{mixer_id}_impeller",
                        "position_m": mixer.get("impeller_position_m", 1.0),
                        "diameter_m": mixer.get("impeller_diameter_m", 0.5),
                        "effective_mrf_radius": mixer.get("effective_mrf_radius", 0.275),
                        "effective_mrf_height": mixer.get("effective_mrf_height", 0.25),
                        "mrf_zone_shape": mixer.get("mrf_zone_shape", "cylinder"),
                        "mrf_zone_surface": mixer.get("mrf_zone_surface"),
                    }
                ]

            for imp in impellers:
                action = self._generate_cellzone_action(mixer, imp)
                if action:
                    actions.append(action)

        return actions

    def _generate_cellzone_action(
        self,
        mixer: dict[str, Any],
        impeller: dict[str, Any],
    ) -> str | None:
        """Generate topoSetDict action for a single impeller cellZone.

        Args:
            mixer: Mixer context dictionary.
            impeller: Impeller context dictionary.

        Returns:
            topoSetDict action string, or None if surface-based.
        """
        cell_zone = f"impellerZone_{impeller['id']}"
        zone_shape = impeller.get("mrf_zone_shape", "cylinder")

        if zone_shape == "surface":
            # Surface-based zone requires separate STL handling
            stl_path = impeller.get("mrf_zone_surface")
            if stl_path:
                return self._generate_surface_cellzone_action(cell_zone, stl_path)
            return None

        # Cylindrical zone (default)
        return self._generate_cylinder_cellzone_action(mixer, impeller, cell_zone)

    def _generate_cylinder_cellzone_action(
        self,
        mixer: dict[str, Any],
        impeller: dict[str, Any],
        cell_zone: str,
    ) -> str:
        """Generate cylinderToCell action for MRF zone.

        Args:
            mixer: Mixer context dictionary.
            impeller: Impeller context dictionary.
            cell_zone: Name of the cellZone to create.

        Returns:
            topoSetDict action string.
        """
        # Get MRF zone dimensions
        radius = impeller.get("effective_mrf_radius", 0.275)
        height = impeller.get("effective_mrf_height", 0.25)
        half_height = height / 2

        # Calculate cylinder endpoints
        mount_pos = mixer.get("mount_position", {"x": 0, "y": 0, "z": 0})
        shaft_axis = mixer.get("shaft_axis", {"x": 0, "y": 0, "z": -1})
        imp_position_m = impeller.get("position_m", 1.0)

        # Impeller center
        center_x = mount_pos["x"] + shaft_axis["x"] * imp_position_m
        center_y = mount_pos["y"] + shaft_axis["y"] * imp_position_m
        center_z = mount_pos["z"] + shaft_axis["z"] * imp_position_m

        # Normalize axis
        axis_mag = math.sqrt(shaft_axis["x"] ** 2 + shaft_axis["y"] ** 2 + shaft_axis["z"] ** 2)
        if axis_mag > 0:
            ax = shaft_axis["x"] / axis_mag
            ay = shaft_axis["y"] / axis_mag
            az = shaft_axis["z"] / axis_mag
        else:
            ax, ay, az = 0, 0, -1

        # Cylinder endpoints: center +/- half_height * axis
        p1_x = center_x - ax * half_height
        p1_y = center_y - ay * half_height
        p1_z = center_z - az * half_height

        p2_x = center_x + ax * half_height
        p2_y = center_y + ay * half_height
        p2_z = center_z + az * half_height

        return f"""
    // MRF zone for impeller {impeller['id']}
    {{
        name            {cell_zone}Set;
        type            cellSet;
        action          new;
        source          cylinderToCell;
        p1              ({p1_x:.6f} {p1_y:.6f} {p1_z:.6f});
        p2              ({p2_x:.6f} {p2_y:.6f} {p2_z:.6f});
        radius          {radius:.6f};
    }}

    {{
        name            {cell_zone};
        type            cellZoneSet;
        action          new;
        set             {cell_zone}Set;
    }}
"""

    def _generate_surface_cellzone_action(
        self,
        cell_zone: str,
        stl_path: str,
    ) -> str:
        """Generate surfaceToCell action for MRF zone from STL.

        Args:
            cell_zone: Name of the cellZone to create.
            stl_path: Path to STL/OBJ file defining the zone surface.

        Returns:
            topoSetDict action string.
        """
        return f"""
    // MRF zone from surface {stl_path}
    {{
        name            {cell_zone}Set;
        type            cellSet;
        action          new;
        source          surfaceToCell;
        file            "{stl_path}";
        outsidePoints   ();  // Points outside the surface
        includeCut      true;
        includeInside   true;
        includeOutside  false;
        nearDistance    0;
        curvature       0.9;
    }}

    {{
        name            {cell_zone};
        type            cellZoneSet;
        action          new;
        set             {cell_zone}Set;
    }}
"""


def generate_mrf_boundary_conditions(
    mixers: list[dict[str, Any]],
) -> dict[str, str]:
    """Generate boundary condition patches for MRF zones.

    For patches inside MRF zones (impeller surfaces), use MRFnoSlip.

    Args:
        mixers: List of mechanical mixer context dictionaries.

    Returns:
        Dictionary mapping patch names to BC type strings.
    """
    bcs = {}

    for mixer in mixers:
        mixer_id = mixer["id"]
        impellers = mixer.get("impellers", [])

        if not impellers:
            # Legacy mode
            patch_name = f"impeller_{mixer_id}"
            bcs[patch_name] = "MRFnoSlip"
        else:
            for imp in impellers:
                patch_name = f"impeller_{imp['id']}"
                bcs[patch_name] = "MRFnoSlip"

    return bcs


def write_mrf_properties(
    case_dir: Path,
    ctx: dict[str, Any],
) -> bool:
    """Convenience function to write MRF properties.

    Args:
        case_dir: OpenFOAM case directory.
        ctx: Configuration context from CaseBuilder.

    Returns:
        True if MRF files were generated.
    """
    generator = MRFGenerator()
    return generator.generate(case_dir, ctx)
