"""QMD report generator for mixing analysis results.

Generates Quarto markdown (.qmd) files with embedded code cells that:
- Read postProcessing data at render time
- Generate R-N curves and statistics
- Produce a git-native, reproducible report artifact

Reports can be rendered to PDF/HTML via `quarto render`.
"""

from datetime import datetime
from pathlib import Path
from typing import Any


class QMDReportGenerator:
    """Generate QMD reports from mixing analysis results."""

    def generate(
        self,
        config_id: str,
        case_dir: Path,
        output_path: Path | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> Path:
        """Generate QMD report.

        Args:
            config_id: Configuration ID for the analysis.
            case_dir: OpenFOAM case directory with results.
            output_path: Output QMD file path. Defaults to case_dir/report.qmd.
            metadata: Optional metadata (project name, client, etc.).

        Returns:
            Path to generated QMD file.
        """
        if output_path is None:
            output_path = Path(case_dir) / "report.qmd"

        if metadata is None:
            metadata = {}

        content = self._generate_content(config_id, case_dir, metadata)

        output_path.write_text(content)
        return output_path

    def _generate_content(
        self,
        config_id: str,
        case_dir: Path,
        metadata: dict[str, Any],
    ) -> str:
        """Generate QMD content."""
        project_name = metadata.get("project_name", "Mixing Analysis")
        date = datetime.now().strftime("%Y-%m-%d")

        return f'''---
title: "{project_name}"
subtitle: "CFD Mixing Analysis Report"
author: "Generated by mixing-cfd-mcp"
date: "{date}"
format:
  html:
    toc: true
    toc-depth: 3
    code-fold: true
  pdf:
    toc: true
    colorlinks: true
execute:
  echo: false
  warning: false
---

## Executive Summary

This report presents the CFD mixing analysis results for configuration `{config_id}`.

```{{python}}
#| label: setup
#| include: false

from pathlib import Path

# mixing_cfd_mcp should be installed (pip install mixing-cfd-mcp)
# or run from development environment
try:
    from mixing_cfd_mcp.analysis import ResultParser, RNCurveAnalyzer, KPIExtractor
except ImportError:
    import sys
    # Fallback for development: try common source locations
    for try_path in [
        Path("{case_dir}").parent.parent / "src",
        Path.home() / "processeng" / "mixing-cfd-mcp" / "src",
    ]:
        if try_path.exists():
            sys.path.insert(0, str(try_path))
            break
    from mixing_cfd_mcp.analysis import ResultParser, RNCurveAnalyzer, KPIExtractor

import numpy as np
import matplotlib.pyplot as plt

case_dir = Path("{case_dir}")
parser = ResultParser(case_dir)
rn_analyzer = RNCurveAnalyzer(case_dir)
```

## Configuration Summary

```{{python}}
#| label: config-summary

# Load configuration if available
config_file = case_dir / "config.json"
if config_file.exists():
    import json
    with open(config_file) as f:
        config = json.load(f)

    print(f"**Configuration ID:** {{config.get('id', 'N/A')}}")
    print(f"**Name:** {{config.get('name', 'N/A')}}")

    if 'tank' in config:
        tank = config['tank']
        print(f"\\n**Tank Geometry:**")
        print(f"- Shape: {{tank.get('shape', 'N/A')}}")
        if tank.get('diameter_m'):
            print(f"- Diameter: {{tank['diameter_m']:.2f}} m")
        if tank.get('height_m'):
            print(f"- Height: {{tank['height_m']:.2f}} m")
else:
    print("Configuration file not found.")
```

## Velocity Analysis

### Velocity R-N Curve

The R-N curve shows the cumulative volume fraction below a given velocity threshold.
Dead zones are identified as regions with velocity below 0.01 m/s.

```{{python}}
#| label: fig-velocity-rn
#| fig-cap: "Velocity R-N Curve"

velocity_rn = rn_analyzer.compute_velocity_rn_curve()

if velocity_rn is not None:
    fig, ax = plt.subplots(figsize=(8, 5))

    ax.plot(velocity_rn.values, velocity_rn.cumulative_fraction * 100,
            'b-', linewidth=2, label='R-N Curve')

    # Mark quantiles
    ax.axhline(y=10, color='gray', linestyle='--', alpha=0.5)
    ax.axhline(y=50, color='gray', linestyle='--', alpha=0.5)
    ax.axhline(y=90, color='gray', linestyle='--', alpha=0.5)

    ax.axvline(x=velocity_rn.q10, color='r', linestyle=':', alpha=0.7,
               label=f'V10 = {{velocity_rn.q10:.3f}} m/s')
    ax.axvline(x=velocity_rn.q50, color='g', linestyle=':', alpha=0.7,
               label=f'V50 = {{velocity_rn.q50:.3f}} m/s')
    ax.axvline(x=velocity_rn.q90, color='orange', linestyle=':', alpha=0.7,
               label=f'V90 = {{velocity_rn.q90:.3f}} m/s')

    # Dead zone threshold
    ax.axvline(x=0.01, color='red', linestyle='-', linewidth=2, alpha=0.8,
               label='Dead zone threshold')

    ax.set_xlabel('Velocity Magnitude (m/s)')
    ax.set_ylabel('Cumulative Volume Fraction (%)')
    ax.set_title('Velocity R-N Curve')
    ax.legend(loc='lower right')
    ax.grid(True, alpha=0.3)
    ax.set_xlim(left=0)
    ax.set_ylim(0, 100)

    plt.tight_layout()
    plt.show()
else:
    print("Velocity histogram data not available.")
```

### Velocity Statistics

```{{python}}
#| label: tbl-velocity-stats
#| tbl-cap: "Velocity Statistics"

velocity_stats = rn_analyzer.get_velocity_stats()

if velocity_stats:
    print("| Metric | Value | Unit |")
    print("|--------|-------|------|")
    print(f"| Mean Velocity | {{velocity_stats['mean_velocity_m_s']:.4f}} | m/s |")
    print(f"| Std Deviation | {{velocity_stats['std_velocity_m_s']:.4f}} | m/s |")
    print(f"| V10 (10th percentile) | {{velocity_stats['v10_m_s']:.4f}} | m/s |")
    print(f"| V50 (Median) | {{velocity_stats['v50_m_s']:.4f}} | m/s |")
    print(f"| V90 (90th percentile) | {{velocity_stats['v90_m_s']:.4f}} | m/s |")
else:
    print("Velocity statistics not available.")
```

## Age Analysis (Liquid Mean Age)

### Age R-N Curve

The age R-N curve shows the distribution of fluid residence time in the tank.

```{{python}}
#| label: fig-age-rn
#| fig-cap: "Age R-N Curve"

age_rn = rn_analyzer.compute_age_rn_curve()

if age_rn is not None:
    fig, ax = plt.subplots(figsize=(8, 5))

    # Convert to hours for display
    age_hours = age_rn.values / 3600

    ax.plot(age_hours, age_rn.cumulative_fraction * 100,
            'b-', linewidth=2, label='R-N Curve')

    # Mark quantiles
    ax.axhline(y=10, color='gray', linestyle='--', alpha=0.5)
    ax.axhline(y=50, color='gray', linestyle='--', alpha=0.5)
    ax.axhline(y=90, color='gray', linestyle='--', alpha=0.5)

    ax.axvline(x=age_rn.q10/3600, color='r', linestyle=':', alpha=0.7,
               label=f'τ10 = {{age_rn.q10/3600:.2f}} h')
    ax.axvline(x=age_rn.q50/3600, color='g', linestyle=':', alpha=0.7,
               label=f'τ50 = {{age_rn.q50/3600:.2f}} h')
    ax.axvline(x=age_rn.q90/3600, color='orange', linestyle=':', alpha=0.7,
               label=f'τ90 = {{age_rn.q90/3600:.2f}} h')

    ax.set_xlabel('Age (hours)')
    ax.set_ylabel('Cumulative Volume Fraction (%)')
    ax.set_title('Age R-N Curve')
    ax.legend(loc='lower right')
    ax.grid(True, alpha=0.3)
    ax.set_xlim(left=0)
    ax.set_ylim(0, 100)

    plt.tight_layout()
    plt.show()
else:
    print("Age histogram data not available.")
```

### Age Statistics

```{{python}}
#| label: tbl-age-stats
#| tbl-cap: "Age Statistics"

# Load config for theoretical HRT
config_file = case_dir / "config.json"
theoretical_hrt_s = None

if config_file.exists():
    import json
    with open(config_file) as f:
        config = json.load(f)
    # Calculate theoretical HRT if tank volume and flow are available
    if 'tank' in config and 'process_inlets' in config:
        # This is simplified - actual implementation would compute volume
        pass

age_stats = rn_analyzer.get_age_stats(theoretical_hrt_s=theoretical_hrt_s)

if age_stats:
    print("| Metric | Value | Unit | Description |")
    print("|--------|-------|------|-------------|")
    print(f"| τ_outlet (Flow-weighted) | {{age_stats.get('tau_outlet_h', age_stats['mean_age_h']):.2f}} | h | Mean age at outlet |")
    print(f"| Mean Age (Volume-weighted) | {{age_stats['mean_age_h']:.2f}} | h | From histogram |")
    print(f"| τ10 (10th percentile) | {{age_stats.get('tau_10_s', 0)/3600:.2f}} | h | - |")
    print(f"| τ50 (Median) | {{age_stats['tau_50_h']:.2f}} | h | - |")
    print(f"| τ90 (90th percentile) | {{age_stats.get('tau_90_s', 0)/3600:.2f}} | h | - |")
    if 'theoretical_hrt_h' in age_stats:
        print(f"| Theoretical HRT | {{age_stats['theoretical_hrt_h']:.2f}} | h | V/Q |")
        print(f"| Effective Volume Ratio | {{age_stats['effective_volume_ratio']:.2f}} | - | V_eff/V |")
    if 'tau_outlet_source' in age_stats:
        print(f"\\n*Note: τ_outlet from {{age_stats['tau_outlet_source']}} (outlet surfaceFieldValue not available)*")
else:
    print("Age statistics not available.")
```

## Dead Zone Analysis

```{{python}}
#| label: dead-zones

dead_zones = rn_analyzer.compute_dead_zones(velocity_threshold=0.01)

if dead_zones:
    print(f"**Dead Zone Analysis (velocity < {{dead_zones.velocity_threshold}} m/s)**")
    print(f"")
    print(f"- Dead Zone Fraction: **{{dead_zones.dead_zone_fraction*100:.1f}}%**")
    print(f"- Dead Zone Volume: {{dead_zones.dead_zone_volume_m3:.1f}} m³")
    print(f"- Total Volume: {{dead_zones.total_volume_m3:.1f}} m³")

    if dead_zones.dead_zone_fraction < 0.10:
        print(f"\\n✅ Dead zone fraction is acceptable (< 10%)")
    elif dead_zones.dead_zone_fraction < 0.15:
        print(f"\\n⚠️ Dead zone fraction is marginal (10-15%)")
    else:
        print(f"\\n❌ Dead zone fraction exceeds target (> 15%)")
else:
    print("Dead zone analysis not available.")
```

## Solver Convergence

```{{python}}
#| label: fig-residuals
#| fig-cap: "Solver Residuals"

residuals = parser.parse_residuals()

if residuals:
    fig, ax = plt.subplots(figsize=(10, 5))

    for field, values in residuals.items():
        ax.semilogy(values, label=field)

    ax.set_xlabel('Iteration')
    ax.set_ylabel('Residual')
    ax.set_title('Solver Convergence')
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()
else:
    print("Residual data not available.")
```

## Conclusions

```{{python}}
#| label: conclusions

velocity_stats = rn_analyzer.get_velocity_stats()
dead_zones = rn_analyzer.compute_dead_zones()

conclusions = []

if velocity_stats:
    if velocity_stats['mean_velocity_m_s'] > 0.01:
        conclusions.append("✅ Mean velocity exceeds minimum threshold")
    else:
        conclusions.append("⚠️ Mean velocity is below minimum threshold")

if dead_zones:
    if dead_zones.dead_zone_fraction < 0.10:
        conclusions.append("✅ Dead zone fraction is within acceptable limits")
    elif dead_zones.dead_zone_fraction < 0.15:
        conclusions.append("⚠️ Dead zone fraction is marginal - consider optimization")
    else:
        conclusions.append("❌ Dead zone fraction exceeds limits - redesign recommended")

if conclusions:
    for c in conclusions:
        print(c)
else:
    print("Insufficient data for conclusions.")
```

---

*Report generated by mixing-cfd-mcp on {date}*
'''
