"""Slice data extraction from OpenFOAM VTK surfaces.

Extracts field data at specified horizontal planes for visualization.
Uses pyvista for VTK parsing when available, with graceful fallback.

Key capabilities:
- Extract U, age, and other fields at specified z-heights
- Interpolate to regular grid for JSON serialization
- Support for multiple slice heights
- Automatic detection of available surfaces
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np


# Try to import pyvista - it's an optional dependency
try:
    import pyvista as pv

    PYVISTA_AVAILABLE = True
except ImportError:
    pv = None  # type: ignore[assignment]
    PYVISTA_AVAILABLE = False


@dataclass
class SliceData:
    """Data extracted from a horizontal slice.

    Contains coordinates and field values interpolated to a regular grid
    for easy JSON serialization and visualization.
    """

    z_height_m: float
    field_name: str

    # Regular grid coordinates
    x_coords: np.ndarray  # 1D array of x coordinates
    y_coords: np.ndarray  # 1D array of y coordinates

    # Field values on the grid (2D array: ny x nx)
    values: np.ndarray

    # Optional: vector components for velocity
    u_component: np.ndarray | None = None
    v_component: np.ndarray | None = None
    w_component: np.ndarray | None = None

    # Statistics
    mean_value: float = 0.0
    min_value: float = 0.0
    max_value: float = 0.0

    # Raw data (if grid interpolation failed)
    raw_x: np.ndarray | None = field(default=None, repr=False)
    raw_y: np.ndarray | None = field(default=None, repr=False)
    raw_values: np.ndarray | None = field(default=None, repr=False)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        result = {
            "z_height_m": self.z_height_m,
            "field_name": self.field_name,
            "x_coords": self.x_coords.tolist(),
            "y_coords": self.y_coords.tolist(),
            "values": self.values.tolist(),
            "statistics": {
                "mean": self.mean_value,
                "min": self.min_value,
                "max": self.max_value,
            },
        }

        # Add vector components if present
        if self.u_component is not None:
            result["vector_components"] = {
                "u": self.u_component.tolist(),
                "v": self.v_component.tolist() if self.v_component is not None else None,
                "w": self.w_component.tolist() if self.w_component is not None else None,
            }

        return result

    @property
    def is_vector_field(self) -> bool:
        """Check if this slice contains vector field data."""
        return self.u_component is not None


@dataclass
class SliceMetadata:
    """Metadata about available slice surfaces."""

    surface_name: str
    z_height_m: float | None
    vtk_path: Path
    available_fields: list[str]
    time: str


class SliceExtractor:
    """Extract field data from OpenFOAM VTK surface outputs.

    Parses VTK files generated by the 'surfaces' function object
    and extracts field values at specified horizontal planes.
    """

    def __init__(self, case_dir: Path):
        """Initialize extractor.

        Args:
            case_dir: OpenFOAM case directory.
        """
        self.case_dir = Path(case_dir)
        self.post_processing_dir = self.case_dir / "postProcessing"

    @staticmethod
    def is_available() -> bool:
        """Check if pyvista is available for VTK parsing."""
        return PYVISTA_AVAILABLE

    def list_available_slices(
        self,
        time: str | None = None,
    ) -> list[SliceMetadata]:
        """List available slice surfaces.

        Args:
            time: Time directory to search. If None, uses latest.

        Returns:
            List of SliceMetadata for available surfaces.
        """
        if not self.post_processing_dir.exists():
            return []

        # Find surfaces function object directories
        surfaces_dirs = list(self.post_processing_dir.glob("*surfaces*"))
        if not surfaces_dirs:
            # Also check for slice-specific names
            surfaces_dirs = list(self.post_processing_dir.glob("slice*"))

        slices = []
        for surfaces_dir in surfaces_dirs:
            if not surfaces_dir.is_dir():
                continue

            # Find time directories
            time_dirs = sorted(
                [d for d in surfaces_dir.iterdir() if d.is_dir() and self._is_time_dir(d)],
                key=lambda d: float(d.name) if d.name.replace(".", "").isdigit() else 0,
            )

            if not time_dirs:
                continue

            # Use specified time or latest
            if time:
                target_dir = surfaces_dir / time
                if not target_dir.exists():
                    continue
            else:
                target_dir = time_dirs[-1]

            # Find VTK files
            vtk_files = list(target_dir.glob("*.vtk")) + list(target_dir.glob("*.vtp"))
            for vtk_file in vtk_files:
                metadata = self._parse_vtk_metadata(vtk_file, target_dir.name)
                if metadata:
                    slices.append(metadata)

        return slices

    def _is_time_dir(self, path: Path) -> bool:
        """Check if path is a time directory (numeric name)."""
        try:
            float(path.name)
            return True
        except ValueError:
            return False

    def _parse_vtk_metadata(
        self,
        vtk_path: Path,
        time: str,
    ) -> SliceMetadata | None:
        """Parse metadata from VTK file.

        Args:
            vtk_path: Path to VTK file.
            time: Time directory name.

        Returns:
            SliceMetadata or None if parsing failed.
        """
        # Extract z-height from surface name if present
        surface_name = vtk_path.stem
        z_height = self._extract_z_height_from_name(surface_name)

        # Get available fields if pyvista available
        available_fields = []
        if PYVISTA_AVAILABLE:
            try:
                mesh = pv.read(vtk_path)
                available_fields = list(mesh.point_data.keys()) + list(mesh.cell_data.keys())
            except Exception:
                pass

        return SliceMetadata(
            surface_name=surface_name,
            z_height_m=z_height,
            vtk_path=vtk_path,
            available_fields=available_fields,
            time=time,
        )

    def _extract_z_height_from_name(self, surface_name: str) -> float | None:
        """Extract z-height from surface name.

        Expected formats:
        - sliceZ_2500mm -> 2.5
        - slice_z_1000 -> 1.0
        - horizontal_2.5 -> 2.5

        Args:
            surface_name: Surface name from VTK file.

        Returns:
            Z-height in meters or None if not parseable.
        """
        import re

        # Pattern: sliceZ_NNNNmm or slice_z_NNNN
        mm_match = re.search(r"[zZ]_?(\d+)\s*mm", surface_name)
        if mm_match:
            return float(mm_match.group(1)) / 1000.0

        # Pattern: z_N.N or Z_N.N or _N.N (meters)
        m_match = re.search(r"[zZ_](\d+\.?\d*)", surface_name)
        if m_match:
            return float(m_match.group(1))

        return None

    def extract_slice(
        self,
        surface_name: str,
        field_name: str = "U",
        time: str | None = None,
        grid_resolution: int = 50,
    ) -> SliceData | None:
        """Extract field data from a named slice surface.

        Args:
            surface_name: Name of the surface (e.g., 'sliceZ_2500mm').
            field_name: Field to extract ('U', 'age', etc.).
            time: Time to extract. If None, uses latest.
            grid_resolution: Number of points per axis for interpolation.

        Returns:
            SliceData object or None if extraction failed.
        """
        if not PYVISTA_AVAILABLE:
            return None

        # Find the VTK file
        vtk_path = self._find_vtk_file(surface_name, time)
        if vtk_path is None:
            return None

        return self._extract_from_vtk(
            vtk_path, field_name, grid_resolution
        )

    def extract_at_height(
        self,
        z_height_m: float,
        field_name: str = "U",
        time: str | None = None,
        grid_resolution: int = 50,
    ) -> SliceData | None:
        """Extract field data at a specific z-height.

        Finds the closest available slice surface to the specified height.

        Args:
            z_height_m: Z-coordinate in meters.
            field_name: Field to extract ('U', 'age', etc.).
            time: Time to extract. If None, uses latest.
            grid_resolution: Number of points per axis for interpolation.

        Returns:
            SliceData object or None if extraction failed.
        """
        if not PYVISTA_AVAILABLE:
            return None

        # List available slices
        slices = self.list_available_slices(time)
        if not slices:
            return None

        # Find closest slice by z-height
        closest_slice = None
        min_distance = float("inf")

        for slice_meta in slices:
            if slice_meta.z_height_m is None:
                continue
            distance = abs(slice_meta.z_height_m - z_height_m)
            if distance < min_distance:
                min_distance = distance
                closest_slice = slice_meta

        if closest_slice is None:
            # No slice with known z-height, try first available
            if slices:
                closest_slice = slices[0]
            else:
                return None

        return self._extract_from_vtk(
            closest_slice.vtk_path, field_name, grid_resolution
        )

    def _find_vtk_file(
        self,
        surface_name: str,
        time: str | None,
    ) -> Path | None:
        """Find VTK file for named surface.

        Args:
            surface_name: Surface name to find.
            time: Time directory to search.

        Returns:
            Path to VTK file or None if not found.
        """
        slices = self.list_available_slices(time)
        for slice_meta in slices:
            if slice_meta.surface_name == surface_name:
                return slice_meta.vtk_path
        return None

    def _extract_from_vtk(
        self,
        vtk_path: Path,
        field_name: str,
        grid_resolution: int,
    ) -> SliceData | None:
        """Extract and interpolate field data from VTK file.

        Args:
            vtk_path: Path to VTK file.
            field_name: Field name to extract.
            grid_resolution: Grid resolution for interpolation.

        Returns:
            SliceData or None if extraction failed.
        """
        if not PYVISTA_AVAILABLE:
            return None

        try:
            mesh = pv.read(vtk_path)
        except Exception:
            return None

        # Get the field data
        field_data = None
        if field_name in mesh.point_data:
            field_data = mesh.point_data[field_name]
        elif field_name in mesh.cell_data:
            # Convert cell data to point data
            mesh = mesh.cell_data_to_point_data()
            if field_name in mesh.point_data:
                field_data = mesh.point_data[field_name]

        if field_data is None:
            # Try alternative names
            alt_names = {
                "U": ["velocity", "Velocity", "U"],
                "age": ["age", "Age", "s"],
            }
            for alt in alt_names.get(field_name, []):
                if alt in mesh.point_data:
                    field_data = mesh.point_data[alt]
                    break
                elif alt in mesh.cell_data:
                    mesh = mesh.cell_data_to_point_data()
                    if alt in mesh.point_data:
                        field_data = mesh.point_data[alt]
                        break

        if field_data is None:
            return None

        # Extract z-height from surface name
        z_height = self._extract_z_height_from_name(vtk_path.stem)
        if z_height is None:
            # Try to get from mesh bounds
            bounds = mesh.bounds
            z_height = (bounds[4] + bounds[5]) / 2  # Average z

        # Get point coordinates
        points = mesh.points
        x_raw = points[:, 0]
        y_raw = points[:, 1]

        # Handle vector vs scalar fields
        is_vector = len(field_data.shape) > 1 and field_data.shape[1] >= 3
        if is_vector:
            # Use velocity magnitude for main values
            values_raw = np.linalg.norm(field_data, axis=1)
            u_raw = field_data[:, 0]
            v_raw = field_data[:, 1]
            w_raw = field_data[:, 2]
        else:
            values_raw = field_data
            u_raw = v_raw = w_raw = None

        # Create regular grid for interpolation
        x_min, x_max = x_raw.min(), x_raw.max()
        y_min, y_max = y_raw.min(), y_raw.max()

        x_grid = np.linspace(x_min, x_max, grid_resolution)
        y_grid = np.linspace(y_min, y_max, grid_resolution)

        # Interpolate to regular grid
        try:
            from scipy.interpolate import griddata

            X, Y = np.meshgrid(x_grid, y_grid)
            values_grid = griddata(
                (x_raw, y_raw), values_raw, (X, Y), method="linear", fill_value=np.nan
            )

            # Interpolate vector components if present
            u_grid = v_grid = w_grid = None
            if is_vector:
                u_grid = griddata(
                    (x_raw, y_raw), u_raw, (X, Y), method="linear", fill_value=np.nan
                )
                v_grid = griddata(
                    (x_raw, y_raw), v_raw, (X, Y), method="linear", fill_value=np.nan
                )
                w_grid = griddata(
                    (x_raw, y_raw), w_raw, (X, Y), method="linear", fill_value=np.nan
                )

        except ImportError:
            # scipy not available, return raw data
            return SliceData(
                z_height_m=z_height,
                field_name=field_name,
                x_coords=x_raw,
                y_coords=y_raw,
                values=values_raw,
                u_component=u_raw,
                v_component=v_raw,
                w_component=w_raw,
                mean_value=float(np.nanmean(values_raw)),
                min_value=float(np.nanmin(values_raw)),
                max_value=float(np.nanmax(values_raw)),
                raw_x=x_raw,
                raw_y=y_raw,
                raw_values=values_raw,
            )

        # Compute statistics (ignoring NaN)
        mean_val = float(np.nanmean(values_grid))
        min_val = float(np.nanmin(values_grid))
        max_val = float(np.nanmax(values_grid))

        return SliceData(
            z_height_m=z_height,
            field_name=field_name,
            x_coords=x_grid,
            y_coords=y_grid,
            values=values_grid,
            u_component=u_grid,
            v_component=v_grid,
            w_component=w_grid,
            mean_value=mean_val,
            min_value=min_val,
            max_value=max_val,
            raw_x=x_raw,
            raw_y=y_raw,
            raw_values=values_raw,
        )

    def extract_multiple_heights(
        self,
        z_heights_m: list[float],
        field_name: str = "U",
        time: str | None = None,
        grid_resolution: int = 50,
    ) -> dict[float, SliceData]:
        """Extract field data at multiple z-heights.

        Args:
            z_heights_m: List of z-coordinates in meters.
            field_name: Field to extract.
            time: Time to extract.
            grid_resolution: Grid resolution for interpolation.

        Returns:
            Dictionary mapping z-height to SliceData.
        """
        results = {}
        for z in z_heights_m:
            slice_data = self.extract_at_height(
                z, field_name, time, grid_resolution
            )
            if slice_data:
                results[z] = slice_data
        return results


def get_slice_at_height(
    case_dir: Path,
    z_height_m: float,
    field_name: str = "U",
    time: str | None = None,
) -> SliceData | None:
    """Convenience function to extract slice data at a height.

    Args:
        case_dir: OpenFOAM case directory.
        z_height_m: Z-coordinate in meters.
        field_name: Field to extract.
        time: Time to extract.

    Returns:
        SliceData or None if extraction failed.
    """
    extractor = SliceExtractor(case_dir)
    return extractor.extract_at_height(z_height_m, field_name, time)


def list_available_slices(case_dir: Path) -> list[SliceMetadata]:
    """Convenience function to list available slices.

    Args:
        case_dir: OpenFOAM case directory.

    Returns:
        List of SliceMetadata.
    """
    extractor = SliceExtractor(case_dir)
    return extractor.list_available_slices()
